path: ../datasets/construction_safety_v1
train: images/train
val: images/val
test: images/test

names:
  0: Person
  1: helmet
  2: no_helmet
  3: vest
  4: boots
  5: gloves
  6: no_gloves
  7: goggles
